### ISSUE TITLE
Wrong Loading Order of Elements

### ISSUE THREAD

**Issue by Frames13** [bitlands/support#5]
In some lands the order of loading the elements change or do not load (not sure about this, could be behind the mountains) 

Img displayed in the explorer
![image](https://user-images.githubusercontent.com/97166832/156893787-95e47220-9fe2-4f99-896c-aa35a67c4421.png)

Img of the land
![image](https://user-images.githubusercontent.com/97166832/156893814-63f50178-8045-434d-b386-5b6059271fce.png)

**Comment by bitlands** [comment]
Fixed: [https://www.bitlands.art/explorer/b/1/458](https://www.bitlands.art/explorer/b/1/458)
